"""add_request_files

Revision ID: 1c1d2a69f48e
Revises: a6b41ae215a8
Create Date: 2026-06-22 16:11:55.280228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c1d2a69f48e'
down_revision: Union[str, Sequence[str], None] = 'a6b41ae215a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request_files',
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('file_type', sa.String(length=30), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('stored_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_name')
    )
    op.create_index(op.f('ix_request_files_id'), 'request_files', ['id'], unique=False)
    op.create_index(op.f('ix_request_files_request_id'), 'request_files', ['request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_request_files_request_id'), table_name='request_files')
    op.drop_index(op.f('ix_request_files_id'), table_name='request_files')
    op.drop_table('request_files')
    # ### end Alembic commands ###
