"""add uploaded_by to files

Revision ID: 675bbb1c38b1
Revises: e2e81b512a6d
Create Date: 2026-07-15 23:30:59.185212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '675bbb1c38b1'
down_revision: Union[str, Sequence[str], None] = 'e2e81b512a6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('uploaded_by', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_files_uploaded_by'), 'files', ['uploaded_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_files_uploaded_by'), table_name='files')
    op.drop_column('files', 'uploaded_by')
    # ### end Alembic commands ###
