"""migrate_request_to_sqlalchemy2

Revision ID: a6b41ae215a8
Revises: 1c9d2664e766
Create Date: 2026-06-22 16:04:06.484196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a6b41ae215a8'
down_revision: Union[str, Sequence[str], None] = '1c9d2664e766'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('requests', 'status',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('requests', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.create_index(op.f('ix_requests_mobile'), 'requests', ['mobile'], unique=False)
    op.create_index(op.f('ix_requests_status'), 'requests', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_requests_status'), table_name='requests')
    op.drop_index(op.f('ix_requests_mobile'), table_name='requests')
    op.alter_column('requests', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('requests', 'status',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.drop_column('requests', 'updated_at')
    # ### end Alembic commands ###
